OSSitemapBundle:
    resource: "@OSSitemapBundle/Controller/"
    type:     annotation
    prefix:   /

OSRssBundle:
    resource: "@OSRssBundle/Controller/"
    type:     annotation
    prefix:   /

_default_web:
    resource: "@AppWebBundle/Resources/config/routing.yml"
    
_default_admin:
    resource: "@AppAdminBundle/Resources/config/routing.yml"

_error403:
    pattern: /error403
    defaults: { _controller: AppCoreBundle:Error:error403 }