security:
    encoders:
        App\CoreBundle\Entity\User: md5

    providers:
      main:
        entity: { class: App\CoreBundle\Entity\User, property: username }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_MODERATE
        ROLE_MODERATE:    ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATE, ROLE_ADMIN]

    acl:
        connection: default

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        configurator:
            pattern: ^/_configurator
            security: false
            
        login:
            pattern:  ^/admin/login$
            security: false

        secured_admin_area:
            pattern:    ^/admin.*
            access_denied_url: /admin/error403
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path:   /admin/logout
                target: /admin
            anonymous: ~        

        secured_web_area:
            pattern:    ^/.*
            access_denied_url: /error403
            form_login:
                check_path: /login_check
                login_path: /signin
                username_parameter: signin[login]
                password_parameter: signin[password]
            logout:
                path:   /logout
                target: /
            anonymous: ~        

    access_control:
      - { path: /admin.*, roles: [ROLE_MODERATE] }
      - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
