security:
    encoders:
        App\CoreBundle\Entity\User: md5

    providers:
      main:
        entity: { class: App\CoreBundle\Entity\User, property: username }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false
            
        configurator:
            pattern: ^/_configurator
            security: false
            
        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin.*
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path:   /admin/logout
                target: /admin
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
