# index
_admin_home:
    pattern:  /admin
    defaults: { _controller: AppAdminBundle:Default:index }

_admin_category_index:
    pattern: /admin/category
    defaults: { _controller: AppAdminBundle:Category:index }

_admin_post_index:
    pattern: /admin/post
    defaults: { _controller: AppAdminBundle:Post:index }

_admin_comment_index:
    pattern: /admin/comment
    defaults: { _controller: AppAdminBundle:Comment:index }
    
_admin_tag_index:
    pattern: /admin/tag
    defaults: { _controller: AppAdminBundle:Tag:index } 

_admin_user_index:
    pattern: /admin/user
    defaults: { _controller: AppAdminBundle:User:index }
    
_admin_team_index:
    pattern: /admin/team
    defaults: { _controller: AppAdminBundle:Team:index }    

# add
_admin_category_add:
    pattern: /admin/category/add
    defaults: { _controller: AppAdminBundle:Category:add }

_admin_post_add:
    pattern: /admin/post/add
    defaults: { _controller: AppAdminBundle:Post:add }

_admin_comment_add:
    pattern: /admin/comment/add
    defaults: { _controller: AppAdminBundle:Comment:add }

_admin_tag_add:
    pattern: /admin/tag/add
    defaults: { _controller: AppAdminBundle:Tag:add }  

_admin_post_tag_add:
    pattern: /admin/post/{post_id}/tag/add
    defaults: { _controller: AppAdminBundle:Post:addTag }

_admin_team_add:
    pattern: /admin/team/add
    defaults: { _controller: AppAdminBundle:Team:add }  
    
_admin_user_add:
    pattern: /admin/user/add
    defaults: { _controller: AppAdminBundle:User:add }      

# edit
_admin_category_edit:
    pattern: /admin/category/{id}/edit
    defaults: { _controller: AppAdminBundle:Category:edit }

_admin_post_edit:
    pattern: /admin/post/{id}/edit
    defaults: { _controller: AppAdminBundle:Post:edit }

_admin_comment_edit:
    pattern: /admin/comment/{id}/edit
    defaults: { _controller: AppAdminBundle:Comment:edit }

_admin_tag_edit:
    pattern: /admin/tag/{id}/edit
    defaults: { _controller: AppAdminBundle:Tag:edit }

_admin_team_edit:
    pattern: /admin/team/{id}/edit
    defaults: { _controller: AppAdminBundle:Team:edit }
    
_admin_user_edit:
    pattern: /admin/user/{id}/edit
    defaults: { _controller: AppAdminBundle:User:edit }    

# delete
_admin_category_delete:
    pattern: /admin/category/{id}/delete
    defaults: { _controller: AppAdminBundle:Category:delete }

_admin_post_delete:
    pattern: /admin/post/{id}/delete
    defaults: { _controller: AppAdminBundle:Post:delete }

_admin_comment_delete:
    pattern: /admin/comment/{id}/delete
    defaults: { _controller: AppAdminBundle:Comment:delete }

_admin_tag_delete:
    pattern: /admin/tag/{id}/delete
    defaults: { _controller: AppAdminBundle:Tag:delete }

_admin_post_tag_delete:
    pattern: /admin/post/{post_id}/tag/{tag_id}/delete
    defaults: { _controller: AppAdminBundle:Post:deleteTag }

_admin_team_delete:
    pattern: /admin/team/{id}/delete
    defaults: { _controller: AppAdminBundle:Team:delete }

_admin_user_delete:
    pattern: /admin/user/{id}/delete
    defaults: { _controller: AppAdminBundle:User:delete }

# show
_admin_post_show:
    pattern: /admin/post/{id}/show
    defaults: { _controller: AppAdminBundle:Post:show }

#login
_admin_login:
  pattern: /admin/login
  defaults: { _controller: AppAdminBundle:Security:login }
  
_admin_login_check:
  pattern: /admin/login_check

_admin_logout:
  pattern: /admin/logout
